#
# Mean pre-installation
#

- name: Create cache directory
  file: path={{ cache_dir }} state=directory

- name: Download NodeJS setup (per http://learn.mean.io)
  get_url: url=https://deb.nodesource.com/setup dest={{ cache_dir }}/nodejs-setup mode=0755

- name: Install NodeJS (per http://learn.mean.io)
  command: "{{ cache_dir }}/nodejs-setup creates=/etc/apt/sources.list.d/nodesource.list"

- name: Install Mean apt dependencies
  apt: name={{ item }} state=latest
  with_items:
    - nodejs
    - git
    - libfontconfig

#- name: Symlink NodeJS
#  file: src=/usr/bin/nodejs path=/usr/bin/node state=link

- name: Install Mean NPM packages
  npm: name={{ item }} global=yes state=latest
  with_items:
    - npm
    - mean-cli
    - gulp
    - bower

- name: Build Mean
  include: build.yml
  when: mean_src_dir is defined

- name: Configure Mean
  include: configure.yml
  when: mean_dir is defined
  