#
# MeanIO source code build
#

- name: Install MeanIO build dependencies
  apt: name={{ item }} state=latest
  with_items:
    - g++
    - libkrb5-dev

- name: Install MeanIO NPM dependencies
  sudo: no
  command: npm install
  args:
    chdir: "{{ meanio_src_dir }}"

- name: Install MeanIO developer systemd service
  when: meanio_init|default(None) == 'systemd'
  template: src=meanio-developer.service.j2 dest="/etc/systemd/system/meanio-developer.service"
  notify:
  - Reload systemd config
  - Restart MeanIO developer service

- name: Install MeanIO developer upstart service
  when: meanio_init|default(None) == 'upstart'
  template: src=meanio-developer.upstart.j2 dest="/etc/init/meanio-developer.conf"
  notify:
  - Restart MeanIO developer service

- name: Start MeanIO developer service
  service: name=meanio-developer state=started
